/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author gw08e
 */
public class CountriesIveVisited extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CountriesIveVisited.class.getName());

    /**
     * Creates new form CountriesIveVisited
     */
    public CountriesIveVisited() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbCountries = new javax.swing.JComboBox<>();
        cmbCities = new javax.swing.JComboBox<>();
        lbvlDisplayImage = new javax.swing.JLabel();
        lblCapital = new javax.swing.JLabel();
        btnDisplayInfo = new javax.swing.JButton();
        btnShowCitys = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Countries ive Visited");

        jLabel2.setText("Cities ive Visited");

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel3.setText("Countries And Cities ive Visited");

        cmbCountries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCountriesActionPerformed(evt);
            }
        });

        lblCapital.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N

        btnDisplayInfo.setText("Show info and fav pic");
        btnDisplayInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayInfoActionPerformed(evt);
            }
        });

        btnShowCitys.setText("Show Citys");
        btnShowCitys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowCitysActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbvlDisplayImage, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cmbCities, 0, 176, Short.MAX_VALUE)
                                .addComponent(cmbCountries, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(lblCapital, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDisplayInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnShowCitys, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(131, 131, 131))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbCountries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDisplayInfo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbCities, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnShowCitys))
                .addGap(28, 28, 28)
                .addComponent(lblCapital, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbvlDisplayImage, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         try
        {
            Connection con = DriverManager.getConnection ("jdbc:ucanaccess://Data\\CountriesIveVisited.accdb");
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery ("SELECT * FROM CountriesIveVisited");
            
            while (rs.next())
                {

                    cmbCountries.addItem(rs.getString("Countries"));
                    
                }
            //txtDisplayContacts.append("\n");
            //txtDisplayContacts.append("There are "+ no_of_rows + " records in the table");
        }
        catch(SQLException e)
        {
            lblCapital.setText("SQL exception occured" + e);
         }
       
    }//GEN-LAST:event_formWindowOpened

    private void cmbCountriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCountriesActionPerformed
       
    }//GEN-LAST:event_cmbCountriesActionPerformed

    private void btnShowCitysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowCitysActionPerformed
       try
        {
            Connection con = DriverManager.getConnection ("jdbc:ucanaccess://Data\\Citys.accdb");
            Statement stmt = con.createStatement();
            String selectedCountry = cmbCountries.getSelectedItem().toString();
            //This removes the prior choices citys so they dont pill up.
            cmbCities.removeAllItems();
            //Selects only the column that matches the the country name and square brakets allows for spaces such as (el salvador)
            String query = "SELECT [" + selectedCountry + "]FROM Citys"; 
            ResultSet citysFound = stmt.executeQuery(query);
            
            while (citysFound.next())
                {
                    //Gets info from the column with the countrys name
                    String cityName = citysFound.getString(selectedCountry);

                   cmbCities.addItem(cityName);
                   
                }
        }
        catch(SQLException e)
        {
            lblCapital.setText("SQL exception occured" + e);
         }
    /*
        
        //if (cityName != null && !cityName.trim().isEmpty()) {
            cmbCities.addItem(cityName);
        //} */
    
    }//GEN-LAST:event_btnShowCitysActionPerformed

    private void btnDisplayInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayInfoActionPerformed
       
        try
        {
            Connection con = DriverManager.getConnection ("jdbc:ucanaccess://Data\\CountriesIveVisited.accdb");
            Statement stmt = con.createStatement();
            //String selectedCity = cmbCities.getSelectedItem().toString();
            String selectedCountries = cmbCountries.getSelectedItem().toString();
            //ResultSet rs = stmt.executeQuery ("SELECT * FROM CountriesIveVisited");
            ResultSet rs = stmt.executeQuery("SELECT * FROM CountriesIveVisited WHERE Countries = '" + selectedCountries + "'");
            
            while (rs.next())
                {
                    lblCapital.setText("The capital of " + selectedCountries + " is " + rs.getString("Capitals"));
                    String flagPath = "/Flags/" + selectedCountries + ".png";
                    java.net.URL flag = getClass().getResource(flagPath);
                    lbvlDisplayImage.setIcon(new javax.swing.ImageIcon(flag));
                    
                }
        }
        catch(SQLException e)
        {
            lblCapital.setText("SQL exception occured" + e);
         }
       
    }//GEN-LAST:event_btnDisplayInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CountriesIveVisited().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDisplayInfo;
    private javax.swing.JButton btnShowCitys;
    private javax.swing.JComboBox<String> cmbCities;
    private javax.swing.JComboBox<String> cmbCountries;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblCapital;
    private javax.swing.JLabel lbvlDisplayImage;
    // End of variables declaration//GEN-END:variables
}
